### ISSUE TITLE
sqlalchemy-history documentation

### ISSUE THREAD

**Issue by barrust** [corridor/sqlalchemy-history#110]
Thank you for this library, it is really interesting and will fill many needs. The readme has a link to documentation for the `sqlalchemy-continuum` project. Is there documentation for the `sqlachemy-history` library or should the linked documentation be sufficient?

**Comment by indiVar0508** [comment]
Hi @barrust ,

`Thank you for this library, it is really interesting and will fill many needs.`
Glad to hear that 😄.

Yeah we have a separate documentation page, that we maintain [here](https://corridor.github.io/sqlalchemy-history/).

`The readme has a link to documentation for the sqlalchemy-continuum project.`
It seems to be a miss by me I will update readme thanks for pointing that out!
