### ISSUE TITLE
Release 2.0.rc1

### ISSUE THREAD

**Issue by AbdealiLoKo** [corridor/sqlalchemy-history#12]
Finalize on the items we want to release for the new major version.
We have decided to keep the history in github for the previous logic from continuum. But start a new major release where the pypi is named as sqlalchemy-history

- [x] - Add user manual
- [x] - Rename py pkg to sqlalchemy_history
- [x] - Test Workflow validation for MSSQL and oracle 
- [x] - Remove compatibility support for SQLA<1.4
- [x] - Remove compatibility support for Py<= 3.6

**Comment by indiVar0508** [comment]
Closing as beta0 release is complete
