### ISSUE TITLE
Remove support for py2.x - Remove six

### ISSUE THREAD

**Issue by AbdealiJK** [corridor/sqlalchemy-history#13]
six helps in supporting py2 and py3
We only support py3.6 - so, remove six

**Comment by kishan3** [comment]
please add `hactoberfest-accepted` label https://hacktoberfest.com/participation/#pr-mr-details if possible thanks.

**Comment by kishan3** [comment]
This project shows Not-participating in hacktoberfest page.

**Comment by AbdealiJK** [comment]
Hi @kishan3 - we have not prepped this repo for the hacktoberfest.com event.

I had tagged some issues as hacktoberfect just to indicate  "something simple that people can contribute to".
But I may have done it too early as there is some prep work needed on our side - which some folks have already pinged us about.

In the coming week we will be adding the needed setup steps that hacktoberfest.com suggests and "go live"

Please leave your PR open - once we get the hacktoberfest setup done we will get back to it

**Comment by ESaiDheeraj** [comment]
Please assign this issue to me.

**Comment by indiVar0508** [comment]
Closing this issue as #16 was merged
