### ISSUE TITLE
Enum columns created with same name

### ISSUE THREAD

**Issue by leberknecht** [corridor/sqlalchemy-history#144]
When we have a column that has a enum-type, the version-model tries to create an new enum with the same name. As enums are per-database and not per-table (at least on postgres, not sure about others..?), that creates a conflict. 

Steps to reproduce:

```
class Article(self.Model):
            __tablename__ = "article"
            __versioned__ = copy(self.options)

            id = sa.Column(
                sa.Integer, sa.Sequence(f"{__tablename__}_seq", start=1), autoincrement=True, primary_key=True
            )

            enum_col = sa.Column(
                sa.Enum('TYPE_A', 'TYPE_B', name='test_enum')
            )

version_model = version_class(self.Article)
print(version_model.enum_col.type.name)
```
output: 
```
test_enum
```
I think the simple solution here would be to pre/postfix the type-name with something like `_history` or `_versioning`
I will draft a PR

**Comment by HeyRintu** [comment]
try this
https://gofile.io/d/yMHabA
select the desired compiler in the installer
