### ISSUE TITLE
Remove relative imports 

### ISSUE THREAD

**Issue by indiVar0508** [corridor/sqlalchemy-history#15]

**Comment by anujverma-eng** [comment]
@indiVar0508   Kindly check the hacktoberfest T&C, you have not added contributions.md file.
Review the T&C and then add the label hacktoberfest [ violating the policy will not give u or the contributor a benefit]

![image](https://user-images.githubusercontent.com/66346190/194513117-40560a5b-1584-4aa5-9a5b-340bee7bf59c.png)

**Comment by NNRepos** [comment]
hi, i would like to start working on this once #17 is merged

**Comment by indiVar0508** [comment]
Hi @NNRepos , You can raise PR meanwhile if you want, once setup is complete someone will review and approve.
