### ISSUE TITLE
Add contribution.md file to project

### ISSUE THREAD

**Issue by indiVar0508** [corridor/sqlalchemy-history#17]

**Comment by NNRepos** [comment]
hi, i would like to help, please assign me if you're interested 😄

**Comment by indiVar0508** [comment]
Hey @NNRepos, really appreciate the offer for help, currently project is in midst of prep for others to be able to contribute and a lot of different chore items are being setup for hactoberfest, this issue, i'll take care just kept there for me to remember.

You can start raising PR(s) for other project related issues that are open
